services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    build: ./backend
    ports:
      - "8080:8080"
